bases:
- github.com/codius/codius-install/base?ref=openfaas

configMapGenerator:
- name: codius-config
  namespace: openfaas
  env: config.env

vars:
- name: RootDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: codius-config
  fieldref:
    fieldpath: data.root_domain
- name: RuntimeClass
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: codius-config
  fieldref:
    fieldpath: data.runtime_class
