apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-dns
  namespace: acme-dns
  labels:
    app: acme-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-dns
  template:
    metadata:
      labels:
        app: acme-dns
    spec:
      containers:
      - name: acme-dns
        image: joohoi/acme-dns:v0.8
        ports:
        - containerPort: 443
          name: https
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/acme-dns
        - name: data-volume
          mountPath: /var/lib/acme-dns
      volumes:
      - name: config-volume
        configMap:
          name: acme-dns-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: acme-dns-pvc
