apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-dns-pvc
  namespace: acme-dns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Mi
