apiVersion: v1
kind: Service
metadata:
  name: acme-dns
  namespace: acme-dns
spec:
  selector:
    app: acme-dns
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: acme-dns-udp
  namespace: acme-dns
spec:
  type: LoadBalancer
  selector:
    app: acme-dns
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
