apiVersion: v1
kind: Config
clusters:
  - name: codius-auth
    cluster:
      insecure-skip-tls-verify: true
      server: https://codius.example.com/token
users:
  - name: kube-apiserver
current-context: codius-auth
contexts:
- context:
    cluster: codius-auth
    user: kube-apiserver
  name: codius-auth
