apiVersion: v1
kind: Namespace
metadata:
  name: moneyd
---
apiVersion: v1
kind: Service
metadata:
  name: moneyd
  namespace: moneyd
spec:
  type: LoadBalancer
  selector:
    app: moneyd
  ports:
  - protocol: TCP
    port: 7768
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneyd
  namespace: moneyd
  labels:
    app: moneyd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moneyd
  template:
    metadata:
      labels:
        app: moneyd
    spec:
      containers:
      - name: moneyd-xrp
        image: wilsonianbcoil/moneyd-local
        env:
        - name: DEBUG
          value: "*"
        - name: MONEYD_BIND_IP
          value: "0.0.0.0"
        ports:
        - containerPort: 7768
