apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codius-deployer
  namespace: codius
rules:
- apiGroups:
  - core.codius.org
  resources:
  - services
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
