apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codius-host
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - $(CODIUS_HOSTNAME)
    secretName: codius-certificate
  rules:
  - host: $(CODIUS_HOSTNAME)
    http:
      paths:
      - path: /
        backend:
          serviceName: codius-web
          servicePort: 3000
      - path: /.well-known/pay
        backend:
          serviceName: receipt-verifier
          servicePort: 3001
      - path: /api
        backend:
          serviceName: kubernetes
          servicePort: 443
      - path: /token
        backend:
          serviceName: codius-auth
          servicePort: 8080
      - path: /{id:balances/.*:creditReceipt$}
        backend:
          serviceName: receipt-verifier
          servicePort: 3000
      - path: /favicon.ico
        backend:
          serviceName: codius-web
          servicePort: 3000
      - path: /openapi/v2
        backend:
          serviceName: kubernetes
          servicePort: 443
---
# TEMP
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: btp-receiver
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  tls:
  - hosts:
    - $(CODIUS_HOSTNAME)
    secretName: codius-certificate
  rules:
  - host: $(CODIUS_HOSTNAME)
    http:
      paths:
      - path: /btp
        backend:
          serviceName: btp-receiver
          servicePort: 3000
      - path: /spsp
        backend:
          serviceName: btp-receiver
          servicePort: 4000
