apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: codius-host
  namespace: codius-system
spec:
  secretName: codius-host-cert
  issuerRef:
    name: $(ISSUER_NAME)
    kind: Issuer
  commonName: $(CODIUS_HOSTNAME)
  dnsNames:
  - $(CODIUS_HOSTNAME)
  - "*.$(CODIUS_HOSTNAME)"
