apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: codius-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $(EMAIL)
    privateKeySecretRef:
      name: account-private-key-secret
    solvers:
    - dns01:
        acmedns:
          host: http://acme-dns.acme-dns
          accountSecretRef:
            name: acme-dns-solver
            key: acme-dns.json
