resources:
- issuer.yaml
- certificate.yaml

configMapGenerator:
- name: cert-config
  namespace: default
  env: config.env

secretGenerator:
- name: acme-dns-solver
  namespace: codius-system
  files:
  - acme-dns.json

vars:
- name: CODIUS_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cert-config
  fieldref:
    fieldpath: data.hostname
- name: EMAIL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cert-config
  fieldref:
    fieldpath: data.email
- name: ISSUER_NAME
  objref:
    apiVersion: v1alpha2
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt
  fieldref:
    fieldpath: metadata.name

configurations:
- kustomizeconfig.yaml

generatorOptions:
  disableNameSuffixHash: true
