apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kata-deploy
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-kata
        command: [ "bash", "-c", "sed -i 's/machine_type = \"pc\"/machine_type = \"microvm\"/g' /opt/kata-artifacts/opt/kata/share/defaults/kata-containers/configuration-qemu.toml; /opt/kata-artifacts/scripts/kata-deploy.sh install" ]
