apiVersion: apps/v1
kind: Deployment
metadata:
  name: codius-web
spec:
  template:
    spec:
      containers:
      - name: codius-web
        image: codius/codius-web:pr-6-merge
        env:
        - name: PAYMENT_POINTER
          valueFrom:
            configMapKeyRef:
              name: codius-config
              key: proxy_payment_pointer
        - name: RECEIPT_VERIFIER_URI
          valueFrom:
            configMapKeyRef:
              name: codius-config
              key: host_url
