bases:
- github.com/codius/codius-crd-operator/config/default
- github.com/codius/codius-auth/config/base
- github.com/codius/codius-web/config/base
- github.com/wilsonianb/codius-install/manifests/receipt-verifier?ref=operator

patchesStrategicMerge:
- manager_env_patch.yaml
- codius_auth_env_patch.yaml
- codius_web_env_patch.yaml
- receipt_verifier_env_patch.yaml

patchesJson6902:
- target:
    version: v1
    group: rbac.authorization.k8s.io
    kind: Role
    name: manager-role
    namespace: codius-crd-operator-system
  path: replace_namespace.yaml
- target:
    version: v1
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: manager-rolebinding
    namespace: codius-crd-operator-system
  path: replace_namespace.yaml
- target:
    version: v1
    group: networking.k8s.io
    kind: NetworkPolicy
    name: deny-internal-egress
    namespace: codius-crd-operator-system
  path: replace_namespace.yaml

vars:
- name: HELLO_SVC_NAME
  objref:
    kind: Service
    version: v1
    name: hello
  fieldref:
    fieldpath: metadata.name
- name: HELLO_SVC_NAMESPACE
  objref:
    kind: Service
    version: v1
    name: hello
  fieldref:
    fieldpath: metadata.namespace
