bases:
# - github.com/wilsonianb/codius-crd-operator/config/default
- github.com/wilsonianb/codius-crd-operator/config/default?ref=ingress
- github.com/wilsonianb/codius-install/manifests/codius-auth?ref=operator
- github.com/wilsonianb/codius-install/manifests/codius-web?ref=operator
- github.com/wilsonianb/codius-install/manifests/receipt-verifier?ref=operator
# temp
- github.com/wilsonianb/codius-install/manifests/btp-receiver?ref=operator

patchesStrategicMerge:
- manager_env_patch.yaml
- codius_auth_env_patch.yaml
- codius_web_env_patch.yaml
- receipt_verifier_env_patch.yaml
