apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: codius-crd-operator-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: CODIUS_AUTH_URL
          value: http://codius-auth.default.svc.cluster.local:8080/forward
        - name: CODIUS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              # why won't kustomize add the suffix?
              name: codius-operator-config
              key: hostname
        - name: CODIUS_CERT_SECRET
          value: codius-certificate
        # - name: RUNTIME_CLASS_NAME
        #   value: kata-qemu
