apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-verifier
spec:
  template:
    spec:
      containers:
      - name: receipt-verifier
        env:
        - name: SPSP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: codius-config
              key: payment_pointer_url
      - name: redis
        image: redis
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
